apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutor
  labels:
    app: tutor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutor
  template:
    metadata:
      labels:
        app: tutor
    spec:
      containers:
        - name: tutor
          image: username/tutor:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5