apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfaction
  labels:
    app: satisfaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfaction
  template:
    metadata:
      labels:
        app: satisfaction
    spec:
      containers:
        - name: satisfaction
          image: username/satisfaction:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5